{% set name = "asdfghjkl" %}
{% set version = "0.1a4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdfghjkl-{{ version }}.tar.gz
  sha256: a934411a0ffdee6fcdccb19672196498ea6a8e55e3e67abbe67200c84b46ddee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.9.0

test:
  imports:
    - asdfghjkl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kazukiosawa/asdfghjkl
  summary: 'ASDL: Automatic Second-order Differentiation (for Fisher, Gradient covariance, Hessian, Jacobian, and Kernel) Library'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
